using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using DevExpress.Data.Filtering;

namespace DXApplication3.Models
{
    public class DbTable
    {
        public string Name { get; set; }
        public string FileName { get; set; }
        public bool Selected { get; set; }
    }

    public class TableList : ObservableCollection<DbTable>
    {
        public static TableList CreateWithData()
        {
            return new TableList {
                new DbTable {Name = "Abocon   ", FileName = "", Selected = true},
                new DbTable {Name = "Abotrn   ", FileName = "", Selected = true},
                new DbTable {Name = "Addrclen ", FileName = "", Selected = true},
                new DbTable {Name = "Addtvlnk ", FileName = "", Selected = true},
                new DbTable {Name = "Addtvref ", FileName = "", Selected = true},
                new DbTable {Name = "Adhoctpl ", FileName = "", Selected = true},
                new DbTable {Name = "Archive  ", FileName = "", Selected = true},
                new DbTable {Name = "Arcmodes ", FileName = "", Selected = true},
                new DbTable {Name = "Arcref   ", FileName = "", Selected = true},
                new DbTable {Name = "Arcvmode ", FileName = "", Selected = true},
                new DbTable {Name = "Attdesc  ", FileName = "", Selected = true},
                new DbTable {Name = "Audevent ", FileName = "", Selected = true},
                new DbTable {Name = "Awardcon ", FileName = "", Selected = true},
                new DbTable {Name = "Awardpre ", FileName = "", Selected = true},
                new DbTable {Name = "Bankhols ", FileName = "", Selected = true},
                new DbTable {Name = "Bchrprio ", FileName = "", Selected = true},
                new DbTable {Name = "Bctflag  ", FileName = "", Selected = true},
                new DbTable {Name = "Bldchrpr ", FileName = "", Selected = true},
                new DbTable {Name = "Booklimt ", FileName = "", Selected = true},
                new DbTable {Name = "Cancreas ", FileName = "", Selected = true},
                new DbTable {Name = "Cardmand ", FileName = "", Selected = true},
                new DbTable {Name = "Ccexdon  ", FileName = "", Selected = true},
                new DbTable {Name = "Ccsdist  ", FileName = "", Selected = true},
                new DbTable {Name = "Chntimes ", FileName = "", Selected = true},
                new DbTable {Name = "Comchanl ", FileName = "", Selected = true},
                new DbTable {Name = "Comdet   ", FileName = "", Selected = true},
                new DbTable {Name = "Comdfpln ", FileName = "", Selected = true},
                new DbTable {Name = "Comscat  ", FileName = "", Selected = true},
                new DbTable {Name = "Comsetrf ", FileName = "", Selected = true},
                new DbTable {Name = "Comsopt  ", FileName = "", Selected = true},
                new DbTable {Name = "Comsysct ", FileName = "", Selected = true},
                new DbTable {Name = "Comsystm ", FileName = "", Selected = true},
                new DbTable {Name = "Comtrigr ", FileName = "", Selected = true},
                new DbTable {Name = "Countysp ", FileName = "", Selected = true},
                new DbTable {Name = "Datacul2 ", FileName = "", Selected = true},
                new DbTable {Name = "Datacull ", FileName = "", Selected = true},
                new DbTable {Name = "Dbuser   ", FileName = "", Selected = true},
                new DbTable {Name = "Defgrid  ", FileName = "", Selected = true},
                new DbTable {Name = "Deftst   ", FileName = "", Selected = true},
                new DbTable {Name = "Dntrntbs ", FileName = "", Selected = true},
                new DbTable {Name = "Donelig  ", FileName = "", Selected = true},
                new DbTable {Name = "Donemprm ", FileName = "", Selected = true},
                new DbTable {Name = "Donmaint ", FileName = "", Selected = true},
                new DbTable {Name = "Donrfddl ", FileName = "", Selected = true},
                new DbTable {Name = "Donrfedt ", FileName = "", Selected = true},
                new DbTable {Name = "Donrfeml ", FileName = "", Selected = true},
                new DbTable {Name = "Donrffrm ", FileName = "", Selected = true},
                new DbTable {Name = "Donrflnk ", FileName = "", Selected = true},
                new DbTable {Name = "Donrfprp ", FileName = "", Selected = true},
                new DbTable {Name = "Donrfrad ", FileName = "", Selected = true},
                new DbTable {Name = "Donrfrsp ", FileName = "", Selected = true},
                new DbTable {Name = "Donrfsec ", FileName = "", Selected = true},
                new DbTable {Name = "Donrfsum ", FileName = "", Selected = true},
                new DbTable {Name = "Donrftyp ", FileName = "", Selected = true},
                new DbTable {Name = "Dseldate ", FileName = "", Selected = true},
                new DbTable {Name = "Dselsrce ", FileName = "", Selected = true},
                new DbTable {Name = "Dseltab  ", FileName = "", Selected = true},
                new DbTable {Name = "Dseltmpl ", FileName = "", Selected = true},
                new DbTable {Name = "Dseltmrl ", FileName = "", Selected = true},
                new DbTable {Name = "Dttype   ", FileName = "", Selected = true},
                new DbTable {Name = "Emaildet ", FileName = "", Selected = true},
                new DbTable {Name = "Emailkey ", FileName = "", Selected = true},
                new DbTable {Name = "Emaladdr ", FileName = "", Selected = true},
                new DbTable {Name = "Errcode  ", FileName = "", Selected = true},
                new DbTable {Name = "Ethcats  ", FileName = "", Selected = true},
                new DbTable {Name = "Ethorig  ", FileName = "", Selected = true},
                new DbTable {Name = "Exccall  ", FileName = "", Selected = true},
                new DbTable {Name = "Fctcon   ", FileName = "", Selected = true},
                new DbTable {Name = "Gcselect ", FileName = "", Selected = true},
                new DbTable {Name = "Hapostcd ", FileName = "", Selected = true},
                new DbTable {Name = "Helphnts ", FileName = "", Selected = true},
                new DbTable {Name = "Holddept ", FileName = "", Selected = true},
                new DbTable {Name = "Isoctry  ", FileName = "", Selected = true},
                new DbTable {Name = "Jobdays  ", FileName = "", Selected = true},
                new DbTable {Name = "Jobname  ", FileName = "", Selected = true},
                new DbTable {Name = "L62ref   ", FileName = "", Selected = true},
                new DbTable {Name = "L63ref   ", FileName = "", Selected = true},
                new DbTable {Name = "Labelfit ", FileName = "", Selected = true},
                new DbTable {Name = "Lbmrgrle ", FileName = "", Selected = true},
                new DbTable {Name = "Letcancd ", FileName = "", Selected = true},
                new DbTable {Name = "Maildet  ", FileName = "", Selected = true},
                new DbTable {Name = "Mailins  ", FileName = "", Selected = true},
                new DbTable {Name = "Mailslct ", FileName = "", Selected = true},
                new DbTable {Name = "Manident ", FileName = "", Selected = true},
                new DbTable {Name = "Mergecat ", FileName = "", Selected = true},
                new DbTable {Name = "Mergerun ", FileName = "", Selected = true},
                new DbTable {Name = "Mergrule ", FileName = "", Selected = true},
                new DbTable {Name = "Messdets ", FileName = "", Selected = true},
                new DbTable {Name = "Messhelp ", FileName = "", Selected = true},
                new DbTable {Name = "Messtext ", FileName = "", Selected = true},
                new DbTable {Name = "Mmfortyp ", FileName = "", Selected = true},
                new DbTable {Name = "Mobilcms ", FileName = "", Selected = true},
                new DbTable {Name = "Mrgcntrl ", FileName = "", Selected = true},
                new DbTable {Name = "Mrgerrcd ", FileName = "", Selected = true},
                new DbTable {Name = "Mrgfield ", FileName = "", Selected = true},
                new DbTable {Name = "Mrgprfxs ", FileName = "", Selected = true},
                new DbTable {Name = "Mrktdept ", FileName = "", Selected = true},
                new DbTable {Name = "Mrktuser ", FileName = "", Selected = true},
                new DbTable {Name = "Mthcon   ", FileName = "", Selected = true},
                new DbTable {Name = "Mthsid   ", FileName = "", Selected = true},
                new DbTable {Name = "Mthsite  ", FileName = "", Selected = true},
                new DbTable {Name = "Namevar  ", FileName = "", Selected = true},
                new DbTable {Name = "Ncccolor ", FileName = "", Selected = true},
                new DbTable {Name = "Nggrconv ", FileName = "", Selected = true},
                new DbTable {Name = "Nhsiaref ", FileName = "", Selected = true},
                new DbTable {Name = "Nmresdsp ", FileName = "", Selected = true},
                new DbTable {Name = "Nonsescm ", FileName = "", Selected = true},
                new DbTable {Name = "Ooasuppl ", FileName = "", Selected = true},
                new DbTable {Name = "Osdate   ", FileName = "", Selected = true},
                new DbTable {Name = "Panref   ", FileName = "", Selected = true},
                new DbTable {Name = "Pcklot   ", FileName = "", Selected = true},
                new DbTable {Name = "Pcktyp   ", FileName = "", Selected = true},
                new DbTable {Name = "Pcl70ref ", FileName = "", Selected = true},
                new DbTable {Name = "Phonekey ", FileName = "", Selected = true},
                new DbTable {Name = "Placegrid", FileName = "", Selected = true},
                new DbTable {Name = "Pltran   ", FileName = "", Selected = true},
                new DbTable {Name = "Pntychk  ", FileName = "", Selected = true},
                new DbTable {Name = "Postrate ", FileName = "", Selected = true},
                new DbTable {Name = "Prncmnd  ", FileName = "", Selected = true},
                new DbTable {Name = "Procint  ", FileName = "", Selected = true},
                new DbTable {Name = "Proclink ", FileName = "", Selected = true},
                new DbTable {Name = "Procsub  ", FileName = "", Selected = true},
                new DbTable {Name = "Prodcell ", FileName = "", Selected = true},
                new DbTable {Name = "Prodct   ", FileName = "", Selected = true},
                new DbTable {Name = "Provdets ", FileName = "", Selected = true},
                new DbTable {Name = "Pstcdupd ", FileName = "", Selected = true},
                new DbTable {Name = "Ptypbch  ", FileName = "", Selected = true},
                new DbTable {Name = "Pulsedb  ", FileName = "", Selected = true},
                new DbTable {Name = "Pulsrprt ", FileName = "", Selected = true},
                new DbTable {Name = "Q46cntrl ", FileName = "", Selected = true},
                new DbTable {Name = "Qcodes   ", FileName = "", Selected = true},
                new DbTable {Name = "Qjobs    ", FileName = "", Selected = true},
                new DbTable {Name = "Quename  ", FileName = "", Selected = true},
                new DbTable {Name = "Queueref ", FileName = "", Selected = true},
                new DbTable {Name = "Recrcat  ", FileName = "", Selected = true},
                new DbTable {Name = "Refaudit ", FileName = "", Selected = true},
                new DbTable {Name = "Refdescn ", FileName = "", Selected = true},
                new DbTable {Name = "Refdonor ", FileName = "", Selected = true},
                new DbTable {Name = "Refmess  ", FileName = "", Selected = true},
                new DbTable {Name = "Reftable ", FileName = "", Selected = true},
                new DbTable {Name = "Relcheck ", FileName = "", Selected = true},
                new DbTable {Name = "Reprtout ", FileName = "", Selected = true},
                new DbTable {Name = "Retrpool ", FileName = "", Selected = true},
                new DbTable {Name = "Rptparam ", FileName = "", Selected = true},
                new DbTable {Name = "Rpttxt   ", FileName = "", Selected = true},
                new DbTable {Name = "S17odate ", FileName = "", Selected = true},
                new DbTable {Name = "S46ref   ", FileName = "", Selected = true},
                new DbTable {Name = "Samptyp  ", FileName = "", Selected = true},
                new DbTable {Name = "Sccmslct ", FileName = "", Selected = true},
                new DbTable {Name = "Scgenatt ", FileName = "", Selected = true},
                new DbTable {Name = "Scialocn ", FileName = "", Selected = true},
                new DbTable {Name = "Scinsatt ", FileName = "", Selected = true},
                new DbTable {Name = "Scmessdsc", FileName = "", Selected = true},
                new DbTable {Name = "Scmessge ", FileName = "", Selected = true},
                new DbTable {Name = "Scomtmpl ", FileName = "", Selected = true},
                new DbTable {Name = "Scpertab ", FileName = "", Selected = true},
                new DbTable {Name = "Scselsrc ", FileName = "", Selected = true},
                new DbTable {Name = "Scslrlcn ", FileName = "", Selected = true},
                new DbTable {Name = "Scslrlia ", FileName = "", Selected = true},
                new DbTable {Name = "Sctmslrl ", FileName = "", Selected = true},
                new DbTable {Name = "Servpo   ", FileName = "", Selected = true},
                new DbTable {Name = "Sesfndpt ", FileName = "", Selected = true},
                new DbTable {Name = "Sesoutcm ", FileName = "", Selected = true},
                new DbTable {Name = "Sesprdcd ", FileName = "", Selected = true},
                new DbTable {Name = "Sesscmdt ", FileName = "", Selected = true},
                new DbTable {Name = "Sessprio ", FileName = "", Selected = true},
                new DbTable {Name = "Sessprm  ", FileName = "", Selected = true},
                new DbTable {Name = "Sessproc ", FileName = "", Selected = true},
                new DbTable {Name = "Sessrev  ", FileName = "", Selected = true},
                new DbTable {Name = "Simlist  ", FileName = "", Selected = true},
                new DbTable {Name = "Sitedmnd ", FileName = "", Selected = true},
                new DbTable {Name = "Siteprm  ", FileName = "", Selected = true},
                new DbTable {Name = "Sityrseq ", FileName = "", Selected = true},
                new DbTable {Name = "Smsdet   ", FileName = "", Selected = true},
                new DbTable {Name = "Teldet   ", FileName = "", Selected = true},
                new DbTable {Name = "Telnoref ", FileName = "", Selected = true},
                new DbTable {Name = "U06ref   ", FileName = "", Selected = true},
                new DbTable {Name = "Usremail ", FileName = "", Selected = true},
                new DbTable {Name = "Valemail ", FileName = "", Selected = true},
                new DbTable {Name = "Vennowrk ", FileName = "", Selected = true},
                new DbTable {Name = "Vnctyprq ", FileName = "", Selected = true},
                new DbTable {Name = "Waitprm  ", FileName = "", Selected = true},
                new DbTable {Name = "Weightbg ", FileName = "", Selected = true},
                new DbTable {Name = "Weightph ", FileName = "", Selected = true},
                new DbTable {Name = "Weighttm ", FileName = "", Selected = true},
                new DbTable {Name = "Wrdmmdef ", FileName = "", Selected = true}

        };


        }
    }
}
